// Random search over AUTO routines for all four start positions: red right, red left, blue right, blue left.
// Drop this file in scripts/ of caryden/ftc-biobuzz-sim.
// Run: npx tsx scripts/auto-search.ts [candidates=200] [seeds=6] [workers=4] [rngSeed=1]
//
// Each candidate is the sim's default tree for that start position (wall-sweep-pair-right or -left) with randomly
// changed numbers and steps. The partner and the other alliance run their default AUTO. A candidate is scored only on
// AUTO: the alliance's LEAVE, AUTO PARK and TIP points, plus a small bonus for the elements still in the hoppers when
// AUTO ends (a head start for TELEOP). The best 10 of each start position are printed and written to
// auto-search-top10.json, each with its full tree, so you can load it in the sim.
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

type Node = Record<string, any>;
type Side = 'right' | 'left';
type Alliance = 'red' | 'blue';
const ROOT = path.resolve(import.meta.dirname, '..');
const baseFile = (s: Side) => path.join(ROOT, `src/auto/trees/auto/wall-sweep-pair-${s}.json`);
const args = process.argv.slice(2), isWorker = args.includes('--worker'), pos = args.filter(a => !a.startsWith('--'));
const HOPPER_BONUS = 2; // points per element left in the hoppers when AUTO ends; a tie-breaker, not game points

// ---- tree editing helpers ----
function walk(n: Node, f: (n: Node) => void) { f(n); for (const k of ['sequence', 'parallel']) if (n[k]) n[k].children.forEach((c: Node) => walk(c, f)); }
const findId = (root: Node, id: string): Node | null => { let r: Node | null = null; walk(root, n => { if (n.id === id) r = n; }); return r; };
function removeIds(root: Node, ids: string[]) {
  walk(root, n => { for (const k of ['sequence', 'parallel']) if (n[k]) n[k].children = n[k].children.filter((c: Node) => !ids.includes(c.id)); });
}
const quant = (v: number, step: number) => Math.round(v / step) * step;
const rand = (rng: () => number, lo: number, hi: number, step = 0.01) => quant(lo + rng() * (hi - lo), step);

// ---- the knobs of each start position, and how they edit the default tree ----
type Genome = Record<string, number | boolean>;
interface Kind { randomGenome(rng: () => number): Genome; defaults: Genome; build(g: Genome, id: string): Node }
function make(side: Side, edit: (tree: Node, g: Genome, set: (sid: string, p: Record<string, unknown>) => void) => void): (g: Genome, id: string) => Node {
  return (g, id) => {
    const tree = JSON.parse(fs.readFileSync(baseFile(side), 'utf8')) as Node;
    tree.id = id; tree.name = `search ${id}`; tree.description = `Generated by auto-search: ${JSON.stringify(g)}`;
    edit(tree, g, (sid, p) => { const n = findId(tree.root, sid); if (n) Object.assign(n.params, p); });
    return tree;
  };
}
const KINDS: Record<Side, Kind> = {
  right: {
    randomGenome: rng => ({ launchZ: -rand(rng, 1.2, 1.5), launchDx: rand(rng, -0.1, 0.1), firstShots: rng() < 0.7 ? 3 : 4, flower: rng() < 0.75, flowerPush: rand(rng, 0.25, 0.45),
      yawDeg: Math.round(20 + rng() * 20), sweepEnd: rand(rng, 0.25, 0.42), secondSweep: rng() < 0.65, tipWait: rand(rng, 1.5, 3.5, 0.1), rearShots: rng() < 0.8, finishAt: rand(rng, 2, 4.5, 0.5) }),
    defaults: { launchZ: -1.32, launchDx: 0, firstShots: 3, flower: true, flowerPush: 0.35, yawDeg: 30, sweepEnd: 0.31, secondSweep: true, tipWait: 2.6, rearShots: true, finishAt: 2.5 },
    build: make('right', (tree, g, set) => {
      tree.defs.launchAudience = `pose(field.hiveX + ${(g.launchDx as number).toFixed(2)}, ${(g.launchZ as number).toFixed(2)}, -90 + flip)`;
      tree.defs.yaw = `rad(${g.yawDeg})`;
      set('s2', { count: g.firstShots }); set('s5', { power: g.flowerPush }); set('s14', { timeoutSec: g.tipWait }); set('finish', { condition: `clock.remaining <= ${g.finishAt}` });
      for (const s of ['s10', 's16']) set(s, { pose: `pose(-(field.half - ${(g.sweepEnd as number).toFixed(2)}), -wallReach, -150)` });
      if (!g.flower) removeIds(tree.root, ['s3', 'collect-s4']);
      if (!g.secondSweep) removeIds(tree.root, ['s13', 'full-s13', 'full-s14', 'collect-s15']);
      if (!g.rearShots) removeIds(tree.root, ['s17', 's18', 'collect-s19', 's21', 's22']);
    }),
  },
  left: {
    randomGenome: rng => ({ launchDx: -rand(rng, 0.5, 0.75), launchZ: rand(rng, 1.05, 1.3), headingDeg: Math.round(120 + rng() * 20), shots: rng() < 0.8 ? 4 : 3, flower: rng() < 0.75, flowerPush: rand(rng, 0.25, 0.45),
      yawDeg: Math.round(20 + rng() * 20), tipWait: rand(rng, 1.5, 4, 0.1), midSweep: rng() < 0.7, lastCycle: rng() < 0.8, finishAt: rand(rng, 2.5, 5, 0.5) }),
    defaults: { launchDx: -0.62, launchZ: 1.17, headingDeg: 129.4, shots: 4, flower: true, flowerPush: 0.35, yawDeg: 30, tipWait: 3, midSweep: true, lastCycle: true, finishAt: 3 },
    build: make('left', (tree, g, set) => {
      tree.defs.angledRear = `pose(field.hiveX ${(g.launchDx as number) < 0 ? '-' : '+'} ${Math.abs(g.launchDx as number).toFixed(2)}, ${(g.launchZ as number).toFixed(2)}, ${g.headingDeg} + flip)`;
      tree.defs.yaw = `rad(${g.yawDeg})`;
      set('s3', { count: g.shots }); set('s6', { power: g.flowerPush }); set('s11', { timeoutSec: g.tipWait }); set('finish', { condition: `clock.remaining <= ${g.finishAt}` });
      if (!g.flower) removeIds(tree.root, ['s4', 'collect-s5']);
      if (!g.midSweep) removeIds(tree.root, ['collect-s17']);
      if (!g.lastCycle) removeIds(tree.root, ['s21', 's22', 'collect-s23']);
    }),
  },
};

// ---- scoring trees in the simulator (worker side) ----
interface Row { id: string; auto: number; tips: number; hopper: number; leave: number; park: number; firstTip: number; score: number; error?: string }
async function score(trees: Node[], seeds: number[], alliance: Alliance, slot: number): Promise<Row[]> {
  const RAPIER = (await import('@dimforge/rapier3d-compat')).default; await RAPIER.init();
  const { Coach } = await import('../src/auto/coach'); const { DT, Sim } = await import('../src/sim/world'); const { addAutoTree } = await import('../src/auto/onboard');
  const out: Row[] = [];
  for (const tree of trees) {
    try { addAutoTree(tree); } catch (e) { out.push({ id: tree.id, auto: 0, tips: 0, hopper: 0, leave: 0, park: 0, firstTip: 0, score: -1, error: String(e).slice(0, 200) }); continue; }
    let auto = 0, tips = 0, hop = 0, leave = 0, park = 0, firstTip = 0, tipRuns = 0;
    for (const seed of seeds) {
      const sim = new Sim(RAPIER, undefined, 'full', seed, { opponent: true, partners: true }); sim.start();
      const cs = sim.robots.map(r => { const c = new Coach(); if (r.alliance === alliance && r.slot === slot) c.autoOverride = tree.id; return c; });
      let tipAt = -1;
      while (sim.phase === 'auto') { sim.step(cs.map((c, i) => c.update(sim.view(i), DT)), cs.map(() => true)); if (tipAt < 0 && sim.hives[alliance].tips > 0) tipAt = 30 - sim.timer; }
      const s = sim.score(alliance); auto += s.leave + s.autoPark + s.autoTips; tips += s.autoTips / 20; leave += s.leave; park += s.autoPark;
      hop += sim.robots.filter(r => r.alliance === alliance).reduce((n, r) => n + r.carried.length, 0) / 2; if (tipAt >= 0) { firstTip += tipAt; tipRuns++; }
    }
    const n = seeds.length;
    out.push({ id: tree.id, auto: auto / n, tips: tips / n, hopper: hop / n, leave: leave / n, park: park / n, firstTip: tipRuns ? firstTip / tipRuns : 0, score: auto / n + HOPPER_BONUS * hop / n });
  }
  return out;
}

if (isWorker) {
  const [file, seedsJson, alliance, slot] = pos;
  console.log(JSON.stringify(await score(JSON.parse(fs.readFileSync(file, 'utf8')), JSON.parse(seedsJson), alliance as Alliance, Number(slot)))); process.exit(0);
}

// ---- orchestrator ----
const [candArg = '200', seedArg = '6', workArg = '4', rngArg = '1'] = pos;
let state = Number(rngArg) >>> 0;
const rng = () => { state = (state + 0x6d2b79f5) >>> 0; let t = state; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
const nCand = Number(candArg), seeds = Array.from({ length: Number(seedArg) }, (_, k) => 3000 + 17 * k), nWork = Math.max(1, Number(workArg));

// One candidate list per side, shared by both alliances. Candidate 0 is the unchanged default, as the yardstick.
const cands: Record<Side, { id: string; genome: Genome; tree: Node }[]> = { right: [], left: [] };
for (const side of ['right', 'left'] as Side[]) {
  cands[side].push({ id: `${side}-000-default`, genome: KINDS[side].defaults, tree: JSON.parse(fs.readFileSync(baseFile(side), 'utf8')) });
  cands[side][0].tree.id = cands[side][0].id;
  for (let i = 1; i < nCand; i++) { const id = `${side}-${String(i).padStart(3, '0')}`, genome = KINDS[side].randomGenome(rng); cands[side].push({ id, genome, tree: KINDS[side].build(genome, id) }); }
}

const tmp = fs.mkdtempSync(path.join(ROOT, 'experiments', '.auto-search-'));
const runWorker = (file: string, alliance: Alliance, slot: number) => new Promise<Row[]>(done => {
  const child = spawn('npx', ['tsx', path.join('scripts', 'auto-search.ts'), '--worker', file, JSON.stringify(seeds), alliance, String(slot)], { cwd: ROOT, stdio: ['ignore', 'pipe', 'inherit'] });
  let o = ''; child.stdout.on('data', d => { o += d; });
  child.on('close', () => { try { done(JSON.parse(o.trim().split('\n').pop()!)); } catch { console.error(`worker for ${file} returned nothing`); done([]); } });
});

const report: Record<string, unknown[]> = {};
for (const alliance of ['red', 'blue'] as Alliance[]) for (const side of ['right', 'left'] as Side[]) {
  const label = `${alliance} ${side}`, slot = side === 'right' ? 0 : 1, list = cands[side];
  const chunks = Array.from({ length: nWork }, (_, w) => list.filter((_, i) => i % nWork === w).map(c => c.tree));
  const files = chunks.map((c, w) => { const f = path.join(tmp, `${alliance}-${side}-${w}.json`); fs.writeFileSync(f, JSON.stringify(c)); return f; });
  const rows = (await Promise.all(files.map(f => runWorker(f, alliance, slot)))).flat().filter(r => !r.error).sort((a, b) => b.score - a.score);
  const base = rows.find(r => r.id.endsWith('-000-default')), top = rows.slice(0, 10), byId = new Map(list.map(c => [c.id, c]));
  console.log(`\n=== ${label} start: ${rows.length}/${nCand} candidates over ${seeds.length} seeds. Default AUTO ${base ? base.auto.toFixed(1) : '?'} pts, score ${base ? base.score.toFixed(1) : '?'} ===`);
  console.log('rank  id                AUTO pts  TIPS  hopper  first TIP (s)  score');
  top.forEach((r, i) => console.log(`${String(i + 1).padStart(4)}  ${r.id.padEnd(16)} ${r.auto.toFixed(1).padStart(8)}  ${r.tips.toFixed(2)}  ${r.hopper.toFixed(2).padStart(6)}  ${r.firstTip.toFixed(1).padStart(13)}  ${r.score.toFixed(1)}`));
  report[label] = top.map(r => ({ ...r, genome: byId.get(r.id)!.genome, tree: byId.get(r.id)!.tree }));
}
fs.rmSync(tmp, { recursive: true, force: true });
fs.writeFileSync(path.join(ROOT, 'auto-search-top10.json'), JSON.stringify(report, null, 1));
console.log('\nWrote auto-search-top10.json (per start position: the top 10 with genome and full tree).');
